@echo off
title Adam Browser - Embedded Chrome Agent v1
echo Starting Adam Browser - Embedded Chrome Agent v1...
echo.
echo 🤖 Initializing AI-powered browser automation...
echo 🌐 Loading embedded Chrome integration...
echo.
cd /d "D:\science_projects\adam_browser"
"C:\Program Files\Python311\python.exe" "D:\science_projects\adam_browser\embedded_chrome_floating_agent_v1.py"
echo.
echo Application closed. Press any key to exit...
pause
